In [212]:
import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [213]:
torch.__version__

'2.8.0+cpu'

### Introduction to Tensors

creating a tensors


In [214]:
# scalar 

scalar = torch.tensor(8)

scalar, scalar.ndim

(tensor(8), 0)

In [215]:
scalar.item()

8

Vector


In [216]:
# vector

vector = torch.tensor([3, 3])

vector, vector.ndim

(tensor([3, 3]), 1)

Matrix


In [217]:
matrix = torch.tensor([[2, 3], [5, 6]])

matrix, matrix.shape, matrix[1]

(tensor([[2, 3],
         [5, 6]]),
 torch.Size([2, 2]),
 tensor([5, 6]))

Tensor


In [218]:
tensor = torch.tensor(
    [
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ],
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ],
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ],
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ]
    ]
)

tensor, tensor.shape

(tensor([[[1, 2],
          [3, 4],
          [5, 6]],
 
         [[1, 2],
          [3, 4],
          [5, 6]],
 
         [[1, 2],
          [3, 4],
          [5, 6]],
 
         [[1, 2],
          [3, 4],
          [5, 6]]]),
 torch.Size([4, 3, 2]))

Random Tensors


In [219]:
### Random Tensors


random_tensor = torch.rand(4, 5)

random_tensor, random_tensor.shape

(tensor([[0.3029, 0.9623, 0.7736, 0.5457, 0.5726],
         [0.9313, 0.4057, 0.5916, 0.0511, 0.0765],
         [0.9313, 0.0735, 0.5207, 0.9768, 0.9563],
         [0.8765, 0.4056, 0.1757, 0.4642, 0.6151]]),
 torch.Size([4, 5]))

In [220]:
# create a random tensor with similar shap to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 4))   # height, width, color channel (R, B, G)

random_image_size_tensor, random_image_size_tensor.shape

(tensor([[[0.6271, 0.1750, 0.4950, 0.6203],
          [0.9776, 0.9366, 0.0899, 0.8034],
          [0.4377, 0.6375, 0.8564, 0.0844],
          ...,
          [0.7858, 0.1064, 0.0545, 0.4066],
          [0.5904, 0.4960, 0.6032, 0.8507],
          [0.3366, 0.9263, 0.8837, 0.6901]],
 
         [[0.2283, 0.1187, 0.1993, 0.1866],
          [0.0096, 0.1536, 0.9869, 0.3137],
          [0.7973, 0.7927, 0.6395, 0.1057],
          ...,
          [0.7516, 0.8101, 0.7031, 0.3271],
          [0.1361, 0.4436, 0.9295, 0.2054],
          [0.6244, 0.9106, 0.3196, 0.7607]],
 
         [[0.9409, 0.8786, 0.7252, 0.3694],
          [0.4572, 0.2763, 0.0329, 0.0304],
          [0.9330, 0.9948, 0.5527, 0.9764],
          ...,
          [0.7754, 0.5448, 0.5318, 0.7895],
          [0.2913, 0.9509, 0.8168, 0.9532],
          [0.2675, 0.7700, 0.7068, 0.4918]],
 
         ...,
 
         [[0.0655, 0.1418, 0.8049, 0.0951],
          [0.5734, 0.1256, 0.1265, 0.6544],
          [0.0114, 0.7377, 0.4556, 0.2458],
      

In [221]:
torch.rand(3, 3)

tensor([[0.3332, 0.5033, 0.7355],
        [0.1122, 0.5045, 0.1045],
        [0.8825, 0.2994, 0.7732]])

In [222]:
zero_tensor = torch.zeros(3, 5, dtype=int)

zero_tensor

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [223]:
ones_tensor = torch.ones(3, 5, dtype=int)

ones_tensor

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [224]:
### creating a range of tensors and tensors like

torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
step = torch.arange(start=0, end=10, step=2)


In [226]:
## creating tensors like

torch.zeros_like(step), torch.ones_like(step)

(tensor([0, 0, 0, 0, 0]), tensor([1, 1, 1, 1, 1]))

### Tensor DataType

**Note** Tensor datatypes is one of the 3 big errors you'will run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors are not on the right device


In [227]:
float_32_tensor = torch.tensor(
    [3.0, 2.0], 
    dtype=None,     
    device=None,    # what device is tensor on
    requires_grad=False  # whether ot not to track gradients with this tensors operation
)

float_32_tensor.dtype

torch.float32

In [228]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor.dtype

torch.float16

In [229]:
float_16_tensor * float_32_tensor

tensor([9., 4.])

In [230]:
int_32_tensor = torch.tensor([3, 4], dtype=torch.long)

int_32_tensor

tensor([3, 4])

In [231]:
float_32_tensor * int_32_tensor

tensor([9., 8.])

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from atensor, can use `tensor.shape`
3. Tensors are not on the right device - to get device from a tensor, can use `tensor.device`


In [232]:
# create a tensor

some_tensor = torch.rand(3, 4)

some_tensor

tensor([[0.3043, 0.9975, 0.7791, 0.8173],
        [0.8452, 0.5536, 0.6583, 0.2873],
        [0.0890, 0.2635, 0.5218, 0.7711]])

In [233]:
# find out details about some tensor

some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### manipulating tensors (tensor operatioins)

#### Tensor Operation include:

1.Addition
2.Subtraction
3.Multiplication (element-wise)
4.Division
5.Matrix Multiplication


In [234]:
# create a tensor and add 10 to it

tensor = torch.tensor([2, 4 , 6])

tensor + 10

tensor([12, 14, 16])

In [235]:
# create a tensor and sub 10 to it

tensor = torch.tensor([2, 4 , 6])

tensor - 10

tensor([-8, -6, -4])

In [236]:
# create a tensor and mult 10 to it

tensor = torch.tensor([2, 4 , 6])

tensor * 10

tensor([20, 40, 60])

In [237]:
torch.matmul(tensor , tensor)

tensor(56)

In [238]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(56)
CPU times: total: 0 ns
Wall time: 1 ms


In [239]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(56)

### There are two main rules that performing matrix multiplication needs to satisfy:

1.the **inner dimensions** must match
2.The resulting matrix has the shape of the **outer dimensions**


In [240]:
# one of the most common erros in deep learning is : shape errors

# shapes for matrix multiplication

tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_b = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

result = torch.mm(tensor_a, tensor_b)  # tensor_b.T is shape (2,3)


torch.mm(tensor_a, tensor_b)    # torch.mma is the same as torch.matmul (it's an alias for writing less code )

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### to fix our tensor shape issues, we can manipulate the shape ofone of our tensors using a **transpose**

### **transpose** switches the axes or dimensions of a given tensor


In [ ]:
tensor_b.T, tensor_b.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([3, 2]))

In [ ]:
torch.matmul(tensor_a, tensor_b.T).shape

torch.Size([3, 3])

In [ ]:
tensor_a @ tensor_b.T

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Finding the min, max, mean, sum etc (tensor aggregation)


In [ ]:
## create a tensor

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [ ]:
# finding mean - note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
# finding sum

torch.sum(x)

tensor(450)

In [ ]:
x.sum()

tensor(450)

### finding the positional min and max


In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the position in tensor that has the minimum value with argmin(), maximum value with argmax() --> return the index of the value
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [ ]:
x[x.argmin()], x[x.argmax()]

(tensor(0), tensor(90))

### Reshaping, stacking, squeezing and unsqueezing tensors

- Reshaping - reshape an input tensor to a defined shape
- View - return a vievw of an input tensor of cerain shape but keep the same memory as the original tensor
- Stacking - coombine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all `1` dimensions from a tensor
- Unsqueeze - add a `1` dimension to a targe tensor
- Permute - Return a view of the iput with dimensions permuted (swapped) in a certain way


In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension

x_reshape = x.reshape(9, 1)
x_reshape, x_reshape.shape, 

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# change the view


z = x.view(9, 1)
z, x

(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [ ]:
# stack tensor on top of each other

x_stack = torch.stack([x, x, x, x], dim=1)

x_stack

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [ ]:
## squeeze

#torch.squeeze() - removes all single dimensions from a targe tensor
x_reshape

tensor([[5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.]])

In [ ]:
torch.Size([1, 9])

torch.Size([1, 9])

In [ ]:
x_reshape.squeeze(),

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])