In [50]:
import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [51]:
torch.__version__

'2.8.0+cpu'

### Introduction to Tensors

creating a tensors


In [52]:
# scalar 

scalar = torch.tensor(8)

scalar, scalar.ndim

(tensor(8), 0)

In [53]:
scalar.item()

8

Vector


In [54]:
# vector

vector = torch.tensor([3, 3])

vector, vector.ndim

(tensor([3, 3]), 1)

Matrix


In [55]:
matrix = torch.tensor([[2, 3], [5, 6]])

matrix, matrix.shape, matrix[1]

(tensor([[2, 3],
         [5, 6]]),
 torch.Size([2, 2]),
 tensor([5, 6]))

Tensor


In [56]:
tensor = torch.tensor(
    [
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ],
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ],
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ],
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ]
    ]
)

tensor, tensor.shape

(tensor([[[1, 2],
          [3, 4],
          [5, 6]],
 
         [[1, 2],
          [3, 4],
          [5, 6]],
 
         [[1, 2],
          [3, 4],
          [5, 6]],
 
         [[1, 2],
          [3, 4],
          [5, 6]]]),
 torch.Size([4, 3, 2]))

Random Tensors


In [57]:
### Random Tensors


random_tensor = torch.rand(4, 5)

random_tensor, random_tensor.shape

(tensor([[0.5978, 0.8550, 0.3753, 0.7882, 0.9433],
         [0.8402, 0.8682, 0.5860, 0.1503, 0.9967],
         [0.5704, 0.1950, 0.0069, 0.1162, 0.1939],
         [0.9385, 0.0387, 0.2947, 0.1346, 0.8459]]),
 torch.Size([4, 5]))

In [58]:
# create a random tensor with similar shap to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 4))   # height, width, color channel (R, B, G)

random_image_size_tensor, random_image_size_tensor.shape

(tensor([[[0.4544, 0.6135, 0.9432, 0.3833],
          [0.0910, 0.4014, 0.5052, 0.7602],
          [0.6538, 0.6422, 0.7686, 0.9741],
          ...,
          [0.3193, 0.9733, 0.9733, 0.9174],
          [0.9879, 0.7355, 0.3229, 0.0617],
          [0.2435, 0.4075, 0.6355, 0.1938]],
 
         [[0.7181, 0.8712, 0.7287, 0.2660],
          [0.2457, 0.8192, 0.8060, 0.2439],
          [0.2182, 0.7991, 0.0149, 0.0284],
          ...,
          [0.9371, 0.3569, 0.1110, 0.2487],
          [0.2487, 0.1562, 0.1608, 0.3864],
          [0.2553, 0.0301, 0.3159, 0.8576]],
 
         [[0.9352, 0.9028, 0.9673, 0.2014],
          [0.9472, 0.3237, 0.7792, 0.3774],
          [0.1061, 0.6244, 0.9649, 0.3271],
          ...,
          [0.1797, 0.9159, 0.0583, 0.2311],
          [0.8665, 0.9234, 0.5912, 0.4557],
          [0.7322, 0.5025, 0.5458, 0.9344]],
 
         ...,
 
         [[0.9054, 0.1598, 0.8756, 0.9108],
          [0.1444, 0.4668, 0.6725, 0.6188],
          [0.2627, 0.4394, 0.8926, 0.9553],
      

In [59]:
torch.rand(3, 3)

tensor([[0.6006, 0.9198, 0.4010],
        [0.8961, 0.2281, 0.0558],
        [0.1984, 0.2530, 0.5096]])

In [60]:
zero_tensor = torch.zeros(3, 5, dtype=int)

zero_tensor

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [61]:
ones_tensor = torch.ones(3, 5, dtype=int)

ones_tensor

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [62]:
### creating a range of tensors and tensors like

torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
step = torch.arange(start=0, end=10, step=2)


In [66]:
## creating tensors like

torch.zeros_like(step), torch.ones_like(step)

(tensor([0, 0, 0, 0, 0]), tensor([1, 1, 1, 1, 1]))

### Tensor DataType

**Note** Tensor datatypes is one of the 3 big errors you'will run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors are not on the right device


In [69]:
float_32_tensor = torch.tensor(
    [3.0, 2.0], 
    dtype=None,     
    device=None,    # what device is tensor on
    requires_grad=False  # whether ot not to track gradients with this tensors operation
)

float_32_tensor.dtype

torch.float32

In [70]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor.dtype

torch.float16

In [71]:
float_16_tensor * float_32_tensor

tensor([9., 4.])

In [77]:
int_32_tensor = torch.tensor([3, 4], dtype=torch.long)

int_32_tensor

tensor([3, 4])

In [78]:
float_32_tensor * int_32_tensor

tensor([9., 8.])

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from atensor, can use `tensor.shape`
3. Tensors are not on the right device - to get device from a tensor, can use `tensor.device`


In [80]:
# create a tensor

some_tensor = torch.rand(3, 4)

some_tensor

tensor([[0.0611, 0.5760, 0.5675, 0.5178],
        [0.6383, 0.1198, 0.7347, 0.0292],
        [0.6022, 0.7860, 0.5922, 0.9488]])

In [81]:
# find out details about some tensor

some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### manipulating tensors (tensor operatioins)

#### Tensor Operation include:

1.Addition
2.Subtraction
3.Multiplication (element-wise)
4.Division
5.Matrix Multiplication


In [84]:
# create a tensor and add 10 to it

tensor = torch.tensor([2, 4 , 6])

tensor + 10

tensor([12, 14, 16])

In [85]:
# create a tensor and sub 10 to it

tensor = torch.tensor([2, 4 , 6])

tensor - 10

tensor([-8, -6, -4])

In [86]:
# create a tensor and mult 10 to it

tensor = torch.tensor([2, 4 , 6])

tensor * 10

tensor([20, 40, 60])