In [89]:
import pandas as pd
import torch
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [90]:
torch.__version__

'2.8.0+cpu'

### Introduction to Tensors

creating a tensors


In [91]:
# scalar 

scalar = torch.tensor(8)

scalar, scalar.ndim

(tensor(8), 0)

In [92]:
scalar.item()

8

Vector


In [93]:
# vector

vector = torch.tensor([3, 3])

vector, vector.ndim

(tensor([3, 3]), 1)

Matrix


In [94]:
matrix = torch.tensor([[2, 3], [5, 6]])

matrix, matrix.shape, matrix[1]

(tensor([[2, 3],
         [5, 6]]),
 torch.Size([2, 2]),
 tensor([5, 6]))

Tensor


In [95]:
tensor = torch.tensor(
    [
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ],
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ],
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ],
        [
            [1, 2], 
            [3, 4], 
            [5, 6]
        ]
    ]
)

tensor, tensor.shape

(tensor([[[1, 2],
          [3, 4],
          [5, 6]],
 
         [[1, 2],
          [3, 4],
          [5, 6]],
 
         [[1, 2],
          [3, 4],
          [5, 6]],
 
         [[1, 2],
          [3, 4],
          [5, 6]]]),
 torch.Size([4, 3, 2]))

Random Tensors


In [96]:
### Random Tensors


random_tensor = torch.rand(4, 5)

random_tensor, random_tensor.shape

(tensor([[0.1850, 0.5815, 0.7115, 0.5633, 0.4231],
         [0.5659, 0.5967, 0.9176, 0.0454, 0.8604],
         [0.6130, 0.1389, 0.9784, 0.8366, 0.5924],
         [0.5419, 0.2798, 0.2001, 0.5617, 0.4221]]),
 torch.Size([4, 5]))

In [97]:
# create a random tensor with similar shap to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 4))   # height, width, color channel (R, B, G)

random_image_size_tensor, random_image_size_tensor.shape

(tensor([[[0.7827, 0.2411, 0.1168, 0.9223],
          [0.2909, 0.3409, 0.2569, 0.0310],
          [0.4804, 0.6590, 0.8550, 0.8887],
          ...,
          [0.6602, 0.8520, 0.1153, 0.9206],
          [0.2298, 0.6652, 0.5377, 0.9418],
          [0.1279, 0.9159, 0.8574, 0.1403]],
 
         [[0.9363, 0.4967, 0.1844, 0.7545],
          [0.4977, 0.6778, 0.2603, 0.0193],
          [0.7001, 0.4646, 0.4670, 0.7826],
          ...,
          [0.4599, 0.9802, 0.2228, 0.2458],
          [0.0434, 0.7368, 0.7399, 0.1576],
          [0.2488, 0.4185, 0.1138, 0.7714]],
 
         [[0.8249, 0.4479, 0.9994, 0.3994],
          [0.3118, 0.7579, 0.5327, 0.0524],
          [0.8137, 0.6080, 0.2806, 0.0304],
          ...,
          [0.4501, 0.7846, 0.7725, 0.2165],
          [0.9918, 0.2841, 0.0258, 0.4039],
          [0.4066, 0.4010, 0.5593, 0.9535]],
 
         ...,
 
         [[0.4727, 0.6684, 0.3747, 0.4452],
          [0.2204, 0.1402, 0.5466, 0.7999],
          [0.9085, 0.6021, 0.6672, 0.1208],
      

In [98]:
torch.rand(3, 3)

tensor([[0.3289, 0.6911, 0.3161],
        [0.1062, 0.3187, 0.1045],
        [0.6274, 0.0094, 0.1738]])

In [99]:
zero_tensor = torch.zeros(3, 5, dtype=int)

zero_tensor

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [100]:
ones_tensor = torch.ones(3, 5, dtype=int)

ones_tensor

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [101]:
### creating a range of tensors and tensors like

torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
step = torch.arange(start=0, end=10, step=2)


In [103]:
## creating tensors like

torch.zeros_like(step), torch.ones_like(step)

(tensor([0, 0, 0, 0, 0]), tensor([1, 1, 1, 1, 1]))

### Tensor DataType

**Note** Tensor datatypes is one of the 3 big errors you'will run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors are not on the right device


In [104]:
float_32_tensor = torch.tensor(
    [3.0, 2.0], 
    dtype=None,     
    device=None,    # what device is tensor on
    requires_grad=False  # whether ot not to track gradients with this tensors operation
)

float_32_tensor.dtype

torch.float32

In [105]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor.dtype

torch.float16

In [106]:
float_16_tensor * float_32_tensor

tensor([9., 4.])

In [107]:
int_32_tensor = torch.tensor([3, 4], dtype=torch.long)

int_32_tensor

tensor([3, 4])

In [108]:
float_32_tensor * int_32_tensor

tensor([9., 8.])

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from atensor, can use `tensor.shape`
3. Tensors are not on the right device - to get device from a tensor, can use `tensor.device`


In [109]:
# create a tensor

some_tensor = torch.rand(3, 4)

some_tensor

tensor([[0.9658, 0.5544, 0.4648, 0.2936],
        [0.0678, 0.9094, 0.3308, 0.9395],
        [0.5331, 0.3046, 0.7253, 0.3999]])

In [110]:
# find out details about some tensor

some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### manipulating tensors (tensor operatioins)

#### Tensor Operation include:

1.Addition
2.Subtraction
3.Multiplication (element-wise)
4.Division
5.Matrix Multiplication


In [111]:
# create a tensor and add 10 to it

tensor = torch.tensor([2, 4 , 6])

tensor + 10

tensor([12, 14, 16])

In [112]:
# create a tensor and sub 10 to it

tensor = torch.tensor([2, 4 , 6])

tensor - 10

tensor([-8, -6, -4])

In [113]:
# create a tensor and mult 10 to it

tensor = torch.tensor([2, 4 , 6])

tensor * 10

tensor([20, 40, 60])

In [114]:
torch.matmul(tensor , tensor)

tensor(56)

In [115]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(56)
CPU times: total: 0 ns
Wall time: 2 ms


In [116]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(56)

### There are two main rules that performing matrix multiplication needs to satisfy:

1.the **inner dimensions** must match
2.The resulting matrix has the shape of the **outer dimensions**


In [117]:
# one of the most common erros in deep learning is : shape errors

# shapes for matrix multiplication

tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_b = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

result = torch.mm(tensor_a, tensor_b)  # tensor_b.T is shape (2,3)


torch.mm(tensor_a, tensor_b)    # torch.mma is the same as torch.matmul (it's an alias for writing less code )

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### to fix our tensor shape issues, we can manipulate the shape ofone of our tensors using a **transpose**

### **transpose** switches the axes or dimensions of a given tensor


In [118]:
tensor_b.T, tensor_b.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([3, 2]))

In [119]:
torch.matmul(tensor_a, tensor_b.T).shape

torch.Size([3, 3])

In [120]:
tensor_a @ tensor_b.T

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Finding the min, max, mean, sum etc (tensor aggregation)


In [121]:
## create a tensor

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [122]:
x.dtype

torch.int64

In [123]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [124]:
# finding mean - note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32))

tensor(45.)

In [125]:
x.type(torch.float32).mean()

tensor(45.)

In [126]:
# finding sum

torch.sum(x)

tensor(450)

In [127]:
x.sum()

tensor(450)

### finding the positional min and max


In [128]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [129]:
# find the position in tensor that has the minimum value with argmin(), maximum value with argmax() --> return the index of the value
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [130]:
x[x.argmin()], x[x.argmax()]

(tensor(0), tensor(90))

### Reshaping, stacking, squeezing and unsqueezing tensors

- Reshaping - reshape an input tensor to a defined shape
- View - return a vievw of an input tensor of cerain shape but keep the same memory as the original tensor
- Stacking - coombine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all `1` dimensions from a tensor
- Unsqueeze - add a `1` dimension to a targe tensor
- Permute - Return a view of the iput with dimensions permuted (swapped) in a certain way


In [131]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [132]:
# add an extra dimension

x_reshape = x.reshape(9, 1)
x_reshape, x_reshape.shape, 

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [133]:
# change the view


z = x.view(9, 1)
z, x

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [134]:
# stack tensor on top of each other

x_stack = torch.stack([x, x, x, x], dim=1)

x_stack

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [135]:
## squeeze

#torch.squeeze() - removes all single dimensions from a targe tensor
x_reshape

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [136]:
torch.Size([1, 9])

torch.Size([1, 9])

In [137]:
x_reshape.squeeze(),

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),)

In [138]:
x_reshape.squeeze().shape

torch.Size([9])

In [139]:
x_squeeze = x_reshape.squeeze()
x_squeeze

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [141]:
# torch.squeeze() - adds a single dimension to a target tensor at a specific dim (dimension)

x_squeeze, x_squeeze.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [144]:
# add an extra dimension with unsqueeze

x_unsqueeze = x_squeeze.unsqueeze(dim=1)
x_unsqueeze, x_unsqueeze.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [145]:
# torch.permute - rearragne the dimnsions of a targe t tensor in a specified order

x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permute = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

x_original.shape, x_permute.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [149]:
x_original[0, 0, 0]

tensor(0.6867)

# Indexing (selecting data from tensors)

- indexing with PyTorch is similar to indexing with NumPy


In [151]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [152]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [154]:
# let's index on the middle bracket (dim=1)

x[0][0], x [0][0][0]

(tensor([1, 2, 3]), tensor(1))

In [155]:
# you can also use ":" to select "all" of a target dimension

x[:, 0]

tensor([[1, 2, 3]])

In [157]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [158]:
# get all values of the - dimension but only the 1 index value of 1st and 2nd dimension

x[:, 1, 1]

tensor([5])

In [159]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension

x[0, 0, 1]

tensor(2)

## PyTorch tensor & Numpy

- NumPy is a popula scientific Python numerical computing library.
- And because of this, PyTorch has functionality to interact with it.

- Data in NumPy, want in PyTorch tensor -> `torch.form_numpy(ndarray)`
- PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [160]:
import numpy as np
import torch

In [161]:
arraay = np.arange(1.0, 8.0)

tensor = torch.from_numpy(arraay)

arraay, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [162]:
# change the value of array, what will this do to 'tensor'?

arraay += 1
arraay, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [163]:
# Tensor to Numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [164]:
# change the tensor 

tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them of better representations of the data -> again -> again -> ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**
Essentially what the ranodm seed does is 'flavour' the randomness


In [165]:
random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

random_tensor_a, random_tensor_b

(tensor([[0.0132, 0.2939, 0.5501, 0.6287],
         [0.6040, 0.5594, 0.5976, 0.1551],
         [0.5990, 0.7015, 0.1056, 0.4349]]),
 tensor([[0.4025, 0.8008, 0.1323, 0.0692],
         [0.8076, 0.7037, 0.1352, 0.4317],
         [0.3973, 0.1513, 0.4465, 0.8700]]))