In [87]:
print("Hello I', excited to learn PyTorch!")

Hello I', excited to learn PyTorch!


In [88]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [89]:
print(torch.__version__)

2.8.0+cpu


# Introduction to Tensor


In [90]:
# scalr

scalar = torch.tensor(7)

scalar

tensor(7)

In [91]:
scalar.ndim

0

In [92]:
# get tensor back as python int

scalar.item()

7

In [93]:
# Vecotr

vector = torch.tensor([7, 7])

vector

tensor([7, 7])

In [94]:
vector.shape

torch.Size([2])

In [95]:
# MATRIX

MATRIX = torch.tensor(
    [
        [7, 8],
        [9, 0]
    ]
)

MATRIX, MATRIX.shape

(tensor([[7, 8],
         [9, 0]]),
 torch.Size([2, 2]))

In [96]:
MATRIX[0],MATRIX[1]

(tensor([7, 8]), tensor([9, 0]))

In [97]:
MATRIX.shape

torch.Size([2, 2])

In [98]:
# Tensor

TENSOR = torch.tensor(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ]
    ]
)


In [99]:
TENSOR, TENSOR.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

# Random Tensors

Why Random Tensors?

Random tesnors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data

start with random numbers -> look at data -> update random number -> look at data -> update random numbers


In [100]:
# create random tensor of size or shape (3, 4)

random_tensor = torch.rand(3, 4)

random_tensor, random_tensor.ndim

(tensor([[0.0810, 0.4113, 0.8175, 0.7612],
         [0.7845, 0.6444, 0.0389, 0.9097],
         [0.1989, 0.3331, 0.5486, 0.2792]]),
 2)

In [101]:
torch.rand(1, 3, 3)

tensor([[[0.3532, 0.3864, 0.1531],
         [0.4629, 0.0689, 0.7430],
         [0.5012, 0.5518, 0.7588]]])

In [102]:
# create a random tensor with similar shape to an image tensor

random_image_tensor = torch.rand(255, 255, 3)

random_image_tensor, random_image_tensor.ndim

(tensor([[[0.8597, 0.3079, 0.1428],
          [0.8554, 0.8824, 0.1418],
          [0.5298, 0.4312, 0.5358],
          ...,
          [0.8946, 0.1866, 0.5667],
          [0.2364, 0.8515, 0.5827],
          [0.8690, 0.0717, 0.8205]],
 
         [[0.3525, 0.0594, 0.5396],
          [0.0257, 0.0255, 0.9309],
          [0.4563, 0.0961, 0.7477],
          ...,
          [0.5709, 0.5016, 0.3908],
          [0.6269, 0.2439, 0.3332],
          [0.9241, 0.2701, 0.8637]],
 
         [[0.3878, 0.9069, 0.8905],
          [0.2770, 0.6868, 0.1229],
          [0.3432, 0.9094, 0.0295],
          ...,
          [0.9538, 0.7570, 0.2656],
          [0.0930, 0.1207, 0.6948],
          [0.7217, 0.6113, 0.7265]],
 
         ...,
 
         [[0.2277, 0.7314, 0.9748],
          [0.9463, 0.9520, 0.7035],
          [0.0916, 0.2499, 0.2031],
          ...,
          [0.1729, 0.2202, 0.2556],
          [0.3602, 0.9938, 0.3674],
          [0.9842, 0.7034, 0.4973]],
 
         [[0.4595, 0.4139, 0.5987],
          [0

# Zeros and Ones


In [103]:
zero = torch.zeros(2, 3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [104]:
from pickletools import int4


ones = torch.ones(3, 3, dtype=int)

ones

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

## Creating a range of tensor and tensor like


In [105]:
torch.arange(3, 33)

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [106]:
range = torch.arange(1, 11, 2)

In [107]:
range, range.shape

(tensor([1, 3, 5, 7, 9]), torch.Size([5]))

In [108]:
# Create tensor like

torch.ones_like(range), torch.zeros_like(range)


(tensor([1, 1, 1, 1, 1]), tensor([0, 0, 0, 0, 0]))

# Tensor datatype


In [113]:
# Float 32 tensor

float_32_tensor = torch.tensor( [3, 6, 9], dtype=torch.float32, device=None, requires_grad=False)

float_32_tensor.dtype, float_32_tensor

(torch.float32, tensor([3., 6., 9.]))

In [115]:
float_16_tensor = torch.tensor(float_32_tensor, dtype=torch.float16)

float_16_tensor.dtype, float_16_tensor

C:\Users\rajun\AppData\Local\Temp\ipykernel_16524\3779483689.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  float_16_tensor = torch.tensor(float_32_tensor, dtype=torch.float16)


(torch.float16, tensor([3., 6., 9.], dtype=torch.float16))