In [41]:
print("Hello I', excited to learn PyTorch!")

Hello I', excited to learn PyTorch!


In [42]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [43]:
print(torch.__version__)

2.8.0+cpu


# Introduction to Tensor


In [44]:
# scalr

scalar = torch.tensor(7)

scalar

tensor(7)

In [45]:
scalar.ndim

0

In [46]:
# get tensor back as python int

scalar.item()

7

In [47]:
# Vecotr

vector = torch.tensor([7, 7])

vector

tensor([7, 7])

In [48]:
vector.shape

torch.Size([2])

In [49]:
# MATRIX

MATRIX = torch.tensor(
    [
        [7, 8],
        [9, 0]
    ]
)

MATRIX, MATRIX.shape

(tensor([[7, 8],
         [9, 0]]),
 torch.Size([2, 2]))

In [50]:
MATRIX[0],MATRIX[1]

(tensor([7, 8]), tensor([9, 0]))

In [51]:
MATRIX.shape

torch.Size([2, 2])

In [52]:
# Tensor

TENSOR = torch.tensor(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ]
    ]
)


In [53]:
TENSOR, TENSOR.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

# Random Tensors

Why Random Tensors?

Random tesnors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data

start with random numbers -> look at data -> update random number -> look at data -> update random numbers


In [59]:
# create random tensor of size or shape (3, 4)

random_tensor = torch.rand(3, 4)

random_tensor, random_tensor.ndim

(tensor([[0.1637, 0.2253, 0.5611, 0.5714],
         [0.1451, 0.3637, 0.7845, 0.5718],
         [0.0404, 0.9029, 0.3536, 0.5927]]),
 2)

In [58]:
torch.rand(1, 3, 3)

tensor([[[0.8982, 0.9532, 0.2317],
         [0.3621, 0.0706, 0.8465],
         [0.2514, 0.1101, 0.5749]]])

In [61]:
# create a random tensor with similar shape to an image tensor

random_image_tensor = torch.rand(255, 255, 3)

random_image_tensor, random_image_tensor.ndim

(tensor([[[0.9881, 0.3922, 0.2499],
          [0.8952, 0.3331, 0.3212],
          [0.3412, 0.7246, 0.2619],
          ...,
          [0.5504, 0.0066, 0.7582],
          [0.3354, 0.0027, 0.2345],
          [0.5764, 0.3404, 0.1503]],
 
         [[0.0552, 0.7760, 0.2465],
          [0.9333, 0.4754, 0.2635],
          [0.4791, 0.8357, 0.8378],
          ...,
          [0.8277, 0.3742, 0.7958],
          [0.9539, 0.6885, 0.2224],
          [0.6278, 0.9432, 0.9863]],
 
         [[0.4575, 0.8649, 0.7497],
          [0.2750, 0.5220, 0.4416],
          [0.0360, 0.9313, 0.5842],
          ...,
          [0.3626, 0.2667, 0.9805],
          [0.7494, 0.0824, 0.2772],
          [0.3116, 0.3111, 0.6970]],
 
         ...,
 
         [[0.0702, 0.6903, 0.2441],
          [0.5201, 0.4314, 0.3397],
          [0.8787, 0.1503, 0.7863],
          ...,
          [0.3231, 0.8296, 0.4181],
          [0.6446, 0.1581, 0.7297],
          [0.7790, 0.3816, 0.1329]],
 
         [[0.3442, 0.7509, 0.1398],
          [0