In [1]:
print("Hello I', excited to learn PyTorch!")

Hello I', excited to learn PyTorch!


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.8.0+cpu


# Introduction to Tensor


In [4]:
# scalr

scalar = torch.tensor(7)

scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# get tensor back as python int

scalar.item()

7

In [7]:
# Vecotr

vector = torch.tensor([7, 7])

vector

tensor([7, 7])

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor(
    [
        [7, 8],
        [9, 0]
    ]
)

MATRIX, MATRIX.shape

(tensor([[7, 8],
         [9, 0]]),
 torch.Size([2, 2]))

In [10]:
MATRIX[0],MATRIX[1]

(tensor([7, 8]), tensor([9, 0]))

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor

TENSOR = torch.tensor(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ]
    ]
)


In [13]:
TENSOR, TENSOR.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

# Random Tensors

Why Random Tensors?

Random tesnors are important because the way many neural networks learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data

start with random numbers -> look at data -> update random number -> look at data -> update random numbers


In [14]:
# create random tensor of size or shape (3, 4)

random_tensor = torch.rand(3, 4)

random_tensor, random_tensor.ndim

(tensor([[0.0754, 0.6019, 0.7400, 0.5912],
         [0.3306, 0.8229, 0.9578, 0.6927],
         [0.2157, 0.8523, 0.9082, 0.2711]]),
 2)

In [15]:
torch.rand(1, 3, 3)

tensor([[[0.5286, 0.5628, 0.7792],
         [0.4629, 0.4787, 0.0820],
         [0.3977, 0.8029, 0.6567]]])

In [16]:
# create a random tensor with similar shape to an image tensor

random_image_tensor = torch.rand(255, 255, 3)

random_image_tensor, random_image_tensor.ndim

(tensor([[[0.3688, 0.0646, 0.9607],
          [0.2393, 0.9118, 0.3006],
          [0.0194, 0.4352, 0.2780],
          ...,
          [0.6353, 0.1877, 0.0711],
          [0.0049, 0.3404, 0.4070],
          [0.5696, 0.7560, 0.8001]],
 
         [[0.8067, 0.5498, 0.0686],
          [0.9361, 0.5819, 0.7715],
          [0.8699, 0.9702, 0.2084],
          ...,
          [0.1264, 0.7921, 0.8265],
          [0.6615, 0.5709, 0.9741],
          [0.1448, 0.7200, 0.7952]],
 
         [[0.1758, 0.5629, 0.3356],
          [0.3735, 0.0529, 0.5574],
          [0.5066, 0.6296, 0.0294],
          ...,
          [0.0494, 0.2031, 0.5768],
          [0.8492, 0.1694, 0.0227],
          [0.9473, 0.5243, 0.8777]],
 
         ...,
 
         [[0.1579, 0.7873, 0.2760],
          [0.8575, 0.0248, 0.1579],
          [0.1878, 0.4965, 0.4828],
          ...,
          [0.8275, 0.8568, 0.5745],
          [0.1236, 0.7814, 0.3688],
          [0.9714, 0.0238, 0.8038]],
 
         [[0.3952, 0.2052, 0.5902],
          [0

# Zeros and Ones


In [17]:
zero = torch.zeros(2, 3)
zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
from pickletools import int4


ones = torch.ones(3, 3, dtype=int)

ones

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

## Creating a range of tensor and tensor like


In [19]:
torch.arange(3, 33)

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [20]:
range = torch.arange(1, 11, 2)

In [21]:
range, range.shape

(tensor([1, 3, 5, 7, 9]), torch.Size([5]))

In [22]:
# Create tensor like

torch.ones_like(range), torch.zeros_like(range)


(tensor([1, 1, 1, 1, 1]), tensor([0, 0, 0, 0, 0]))

# Tensor datatype


In [23]:
# Float 32 tensor

float_32_tensor = torch.tensor( [3, 6, 9], dtype=torch.float32, device=None, requires_grad=False)

float_32_tensor.dtype, float_32_tensor

(torch.float32, tensor([3., 6., 9.]))

In [24]:
float_16_tensor = torch.tensor(float_32_tensor, dtype=torch.float16)

float_16_tensor.dtype, float_16_tensor

C:\Users\rajun\AppData\Local\Temp\ipykernel_21672\3779483689.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  float_16_tensor = torch.tensor(float_32_tensor, dtype=torch.float16)


(torch.float16, tensor([3., 6., 9.], dtype=torch.float16))

In [25]:
some_tensor = torch.rand(4, 4)
some_tensor

tensor([[0.4813, 0.2126, 0.7069, 0.9316],
        [0.3959, 0.1510, 0.0354, 0.3038],
        [0.8559, 0.0079, 0.5021, 0.2989],
        [0.4181, 0.1293, 0.5812, 0.6438]])

In [26]:
print(some_tensor)
print(f'Datatye of tensor:  {some_tensor.dtype}', )
print(f'shape of tensor:  {some_tensor.shape}', )
print(f'device of tensor:  {some_tensor.device}', )

tensor([[0.4813, 0.2126, 0.7069, 0.9316],
        [0.3959, 0.1510, 0.0354, 0.3038],
        [0.8559, 0.0079, 0.5021, 0.2989],
        [0.4181, 0.1293, 0.5812, 0.6438]])
Datatye of tensor:  torch.float32
shape of tensor:  torch.Size([4, 4])
device of tensor:  cpu


### tensor manipulation


In [27]:
tensor = torch.tensor([1, 2, 3, 4, 5])

tensor

tensor([1, 2, 3, 4, 5])

In [28]:
tensor + 10,

(tensor([11, 12, 13, 14, 15]),)

In [29]:

tensor - 2,


(tensor([-1,  0,  1,  2,  3]),)

In [30]:

tensor  * 2,

(tensor([ 2,  4,  6,  8, 10]),)

#### try out PyTorch in-build functions


In [31]:
torch.add(tensor, tensor)

tensor([ 2,  4,  6,  8, 10])

In [32]:
### Matrix Multiplicatino

In [33]:
torch.rand(3, 3) * torch.rand(3, 3)

tensor([[0.0482, 0.6810, 0.5999],
        [0.1070, 0.4394, 0.1859],
        [0.3649, 0.3266, 0.0024]])

In [34]:
a = torch.rand(3, 3)
b = torch.rand(3, 3)

In [35]:
torch.matmul(a, b)

tensor([[0.8382, 0.3427, 0.5931],
        [0.6653, 0.2145, 0.2716],
        [0.4953, 0.6191, 0.8435]])

In [36]:
a @ b

tensor([[0.8382, 0.3427, 0.5931],
        [0.6653, 0.2145, 0.2716],
        [0.4953, 0.6191, 0.8435]])

### Finding the min, max, mean, sum etc (tensor aggregation)


In [37]:

x = torch.arange(0, 100, 10)

In [38]:
x.dtype

torch.int64

In [39]:
torch.min(x)

tensor(0)

In [40]:
torch.max(x)

tensor(90)

In [41]:
torch.mean(x.float())

tensor(45.)

In [42]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max


In [43]:
x.argmin()

tensor(0)

In [44]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, and unsqueezing tensor


In [45]:
x = torch.arange(1, 10)

x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [46]:
x_reshape = x.reshape(1, 9)

x_reshape, x_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [47]:
x_reshape = x.reshape(3, 3)

x_reshape, x_reshape.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [48]:
x = torch.tensor([1, 2, 3, 4, 5])     

x, x.shape

(tensor([1, 2, 3, 4, 5]), torch.Size([5]))

In [49]:
y = x.unsqueeze(0)              

y, y.shape


(tensor([[1, 2, 3, 4, 5]]), torch.Size([1, 5]))

In [50]:
z = x.unsqueeze(1)  

z, z.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5]]),
 torch.Size([5, 1]))

In [51]:

x_original = torch.rand(224, 224, 3)

x_permuted = x_original.permute(2, 0, 1)

print(f"Previours shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previours shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensor)

Indexing with PyTorch is similar to indexing with numpy


In [58]:
# create a tensor

import torch

x = torch.arange(1, 10).reshape(1, 3, 3)

x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [60]:
# let's index on our new tensor

x[0][2]

tensor([7, 8, 9])

In [66]:
x[:,:, 2]

tensor([[3, 6, 9]])