# Matrix and Matrix Operations

In [15]:
import numpy as np

Creating a Matrix using Numpy

In [22]:
matrix_1 = np.array([[2, 3],[6, 7]])

print(matrix_1)

matrix_1.shape

[[2 3]
 [6 7]]


(2, 2)

In [23]:
matrix_2 = np.array([[1, 2, 1], [3, 4, 2] , [5, 6, 4]])

print(matrix_2)

matrix_2.shape

[[1 2 1]
 [3 4 2]
 [5 6 4]]


(3, 3)

Creating matrices with random values

In [21]:
random_matrix = np.random.rand(4, 4)

print(random_matrix)

random_matrix.shape

[[0.12638662 0.54706719 0.68058856 0.26088148]
 [0.9251339  0.46186978 0.40621558 0.72216418]
 [0.51143965 0.33137817 0.68073015 0.55487713]
 [0.01589039 0.42129187 0.61983394 0.82136772]]


(4, 4)

Creating matrices with random integers

In [25]:
random_integer_matrix = np.random.randint(100, size=(3, 3))

print(random_integer_matrix)

random_integer_matrix.shape


[[93 56 40]
 [86 42  1]
 [65 79 22]]


(3, 3)

Matrix with all values as 1

In [30]:
matrix_3 = np.ones((2, 3), dtype=int)

matrix_3

array([[1, 1, 1],
       [1, 1, 1]])

Matrix with all values as o

In [31]:
matrix_4 = np.zeros((3, 4), dtype=int)

matrix_4

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Identity Matrix

In [35]:
identity_matrix = np.eye(3, 3, dtype=int)

identity_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Transpose of Matrix
    - row into columns
    - columns into rows

In [38]:
# matrix with random interger values

a = np.random.randint(100, size=(4, 5))

print(a)
 

[[31 61 90  0 86]
 [35 99 60 81 75]
 [88 89 86 33 85]
 [97 85 83 53 14]]


transpose of a

In [39]:
transpose_a = np.transpose(a)

print(transpose_a)

[[31 35 88 97]
 [61 99 89 85]
 [90 60 86 83]
 [ 0 81 33 53]
 [86 75 85 14]]


In [40]:
transpose_a = a.transpose()

transpose_a

array([[31, 35, 88, 97],
       [61, 99, 89, 85],
       [90, 60, 86, 83],
       [ 0, 81, 33, 53],
       [86, 75, 85, 14]])

## Matrix Operations

#### Adding Two Matrices
    -- Rule: Two Matrices can be added only if the have the same shape, that is, both the matrix should have the same number of rows and columns

Matrix Addition
    - two matrices can be added only if they have same shape

In [59]:
a = np.random.randint(10, size=(2, 2))
b = np.random.randint(10, 20, size=(2, 2))

sum = np.add(a, b)

print("matrix a :\n", a)
print("matrix b : \n", b)
print("sum of matrix a , b: \n", sum)

matrix a :
 [[0 0]
 [8 1]]
matrix b : 
 [[14 16]
 [16 10]]
sum of matrix a , b: 
 [[14 16]
 [24 11]]


Matrix Subtraction
    - two matrices can be added only if they have same shape

In [60]:
a = np.random.randint(10, size=(2, 2))
b = np.random.randint(10, 20, size=(2, 2))

sub = np.subtract(a, b)

print("matrix a :\n", a)
print("matrix b : \n", b)
print("sub of matrix a , b: \n", sub)

matrix a :
 [[8 9]
 [1 2]]
matrix b : 
 [[17 11]
 [13 18]]
sub of matrix a , b: 
 [[ -9  -2]
 [-12 -16]]


Matrix Multiplication

In [62]:
a = np.random.randint(10, size=(2, 3))
b = np.random.randint(10, 20, size=(3, 2))

mult = np.matmul(a, b)

print("matrix a :\n", a)
print("matrix b : \n", b)
print("mult of matrix a , b: \n", sub)

matrix a :
 [[7 7 3]
 [0 6 4]]
matrix b : 
 [[12 14]
 [18 15]
 [12 14]]
mult of matrix a , b: 
 [[ -9  -2]
 [-12 -16]]


Multiplication with scalar

In [64]:
x = 2 
y = np.random.randint(10, size=(3, 3))

mult_scalar = np.multiply(x , y)

mult_scalar

array([[ 6,  8, 14],
       [ 4,  2,  6],
       [16, 12, 16]])