In [93]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cpu


#### Tensors

Tensors are the fundamental data structure in PyTorch, similar to NumPy arrays but with GPU support and autograd capabilities. They are used for all computations, representing data like scalars, vectors, matrices, or higher-dimensional arrays.


In [94]:
scalar = torch.tensor(9)
vector = torch.tensor([8, 9])
matrix = torch.tensor([
    [1., 3., 5.],
    [2., 4., 6.]
])
tensor = torch.tensor([
    [
        [1, 2],
        [3, 4],
        [5, 6],
    ]
])

print(f"Scalar : \n Original Scalar {scalar} \n Shape of Scalar {scalar.ndim} \n ")
print(f"Vector : \n Original Vector {vector} \n Shape of Vector {vector.ndim} \n ")
print(f"Matrix : \n Original Matrix {matrix} \n Shape of Matrix {matrix.ndim} \n ")
print(f"Tensor : \n Original Tensor {tensor} \n Shape of Tensor {tensor.ndim} \n ")

Scalar : 
 Original Scalar 9 
 Shape of Scalar 0 
 
Vector : 
 Original Vector tensor([8, 9]) 
 Shape of Vector 1 
 
Matrix : 
 Original Matrix tensor([[1., 3., 5.],
        [2., 4., 6.]]) 
 Shape of Matrix 2 
 
Tensor : 
 Original Tensor tensor([[[1, 2],
         [3, 4],
         [5, 6]]]) 
 Shape of Tensor 3 
 


#### Random Tensors


In [95]:
random_tensors = torch.rand(4, 5)
random_image_tensor = torch.rand(size=(224, 224, 3))
print(random_tensors, random_tensors.shape, random_tensors.ndim)
print(random_image_tensor, random_image_tensor.shape, random_image_tensor.ndim)

tensor([[0.9266, 0.8501, 0.5952, 0.5625, 0.9802],
        [0.0856, 0.3344, 0.8302, 0.5750, 0.8936],
        [0.6656, 0.5921, 0.6209, 0.3782, 0.0300],
        [0.7316, 0.6332, 0.9703, 0.8884, 0.4063]]) torch.Size([4, 5]) 2
tensor([[[0.9704, 0.0090, 0.9739],
         [0.6662, 0.5070, 0.1831],
         [0.5304, 0.8458, 0.9310],
         ...,
         [0.4719, 0.4635, 0.4980],
         [0.3307, 0.9469, 0.0963],
         [0.1071, 0.1039, 0.4384]],

        [[0.5516, 0.7077, 0.3997],
         [0.8505, 0.4260, 0.6252],
         [0.1089, 0.7733, 0.7027],
         ...,
         [0.7662, 0.4659, 0.2153],
         [0.2009, 0.8007, 0.8076],
         [0.1035, 0.7639, 0.0719]],

        [[0.9183, 0.0487, 0.5940],
         [0.5141, 0.1997, 0.7445],
         [0.1934, 0.6670, 0.1113],
         ...,
         [0.6080, 0.4917, 0.0167],
         [0.6949, 0.2952, 0.2941],
         [0.6813, 0.2906, 0.1295]],

        ...,

        [[0.1594, 0.0767, 0.6900],
         [0.8978, 0.9789, 0.9457],
         [0.5751

#### Zeros/Ones


In [96]:
zeros = torch.zeros(3, 3)
ones = torch.ones(3, 3)

zeros, zeros.shape, zeros.ndim, ones, ones.shape, ones.ndim

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.Size([3, 3]),
 2,
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.Size([3, 3]),
 2)

#### Range


In [97]:
range_tensor = torch.arange(0, 100, 2)
range_tensor

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

#### Data Types


In [98]:
float_32_tensor = torch.tensor([3., 4., 5.], dtype=None)
float_16_tensor = torch.tensor([2., 6., 9.], dtype=torch.float16)
float_32_tensor, float_32_tensor.dtype
float_16_tensor, float_16_tensor.dtype

(tensor([2., 6., 9.], dtype=torch.float16), torch.float16)

In [99]:
# 2 x 3 tensor
tensor = torch.tensor([
    [1., 2., 3],
    [4., 5., 6.]
])

tensor_squared = tensor * 2
tensor_sum = tensor.sum()

print(f"Original Tensor : \n {tensor} \n")
print(f"Squared Tensor : \n {tensor_squared} \n")
print(f"Sum of Tensor : \n {tensor_sum} \n")


Original Tensor : 
 tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

Squared Tensor : 
 tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]]) 

Sum of Tensor : 
 21.0 



#### Manipulating Tensors (tensor Operations)


In [100]:
tensor = torch.tensor([1, 2, 3])

tensor_add = tensor + 10
tensor_sub = tensor - 10
tensor_mult = tensor * 10
tensor_div = tensor / 10

tensor_add, tensor_sub, tensor_mult, tensor_div

(tensor([11, 12, 13]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

#### Matrix Multiplication


In [101]:
a = torch.tensor([2, 4, 6])
b = torch.tensor([1, 3, 5])
result = torch.dot(a, b)
print(result)
print(torch.matmul(a, b))


tensor(44)
tensor(44)


In [102]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
y.backward()
print(f"Gradient of y = x^2 at x = {x} : {x}, {y}, {x.grad}")

Gradient of y = x^2 at x = 3.0 : 3.0, 9.0, 6.0


#### min/max/mean/sum


In [103]:

tensor = torch.arange(0, 100, 2)

print(f"Tensor: {tensor}")
print(f"Min: {torch.min(tensor)}")
print(f"Max: {torch.max(tensor)}")
print(f"Sum: {torch.sum(tensor)}")
print(f"Mean: {tensor.float().mean()}")


Tensor: tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])
Min: 0
Max: 98
Sum: 2450
Mean: 49.0


#### Reshaping, stacking, Squeezing, unsqueeezing


In [104]:
# ReShaping Tensor Reshaping changes the shape (dimensions) of a tensor without altering its data. The total number of elements must remain the same. Use torch.reshape() or .view().

tensor = torch.tensor([1, 2, 3, 4, 5, 6])

reshape = tensor.reshape(2, 3)
print(f"Original Tensor {tensor}")
print(f"Reshaped Tensor {reshape}")

Original Tensor tensor([1, 2, 3, 4, 5, 6])
Reshaped Tensor tensor([[1, 2, 3],
        [4, 5, 6]])


In [105]:
# Stacking Tensor Stacking combines multiple tensors along a new dimension, creating a higher-dimensional tensor. Use torch.stack() to stack tensors of the same shape along a specified axis.



tensor1 = torch.tensor([1, 2, 3, 4, 5])
tensor2 = torch.tensor([6, 7, 8, 9, 0])

stacked = torch.stack((tensor1, tensor2), dim=0)
print(f'stacked tenosr: {stacked}')

stacked tenosr: tensor([[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]])


In [106]:
# Squeezing Squeezing removes dimensions of size 1 from a tensor, reducing its rank. Use torch.squeeze() or .squeeze(). This is useful when a dimension is unnecessary (e.g., batch size of 1).

tensor = torch.tensor([[[1], [2], [3]]])

squeezed = tensor.squeeze()
print("Original tensor shape:", tensor.shape)
print("Squeezed tensor:", squeezed, "with shape:", squeezed.shape)

Original tensor shape: torch.Size([1, 3, 1])
Squeezed tensor: tensor([1, 2, 3]) with shape: torch.Size([3])


In [107]:
# Unsqueeze Unsqueezing adds a dimension of size 1 at a specified index. Use torch.unsqueeze() or .unsqueeze(). This is often used to match tensor shapes for operations like batch processing.

tensor = torch.tensor([1, 2, 3])

unsqueezed = tensor.unsqueeze(0)
print("Original tensor shape:", tensor.shape)
print("Unsqueezed tensor:", unsqueezed, "with shape:", unsqueezed.shape)

Original tensor shape: torch.Size([3])
Unsqueezed tensor: tensor([[1, 2, 3]]) with shape: torch.Size([1, 3])


#### PyTorch tensor & Numpy


In [108]:
import torch
import numpy as np

# NumPy to PyTorch tensor
np_array = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_array)
print("NumPy to Tensor:\n", tensor)

# PyTorch tensor to NumPy
tensor = torch.tensor([[5, 6], [7, 8]])
np_array = tensor.numpy()
print("Tensor to NumPy:\n", np_array)

NumPy to Tensor:
 tensor([[1, 2],
        [3, 4]])
Tensor to NumPy:
 [[5 6]
 [7 8]]


#### ReProducability


In [109]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor1 = torch.rand(2, 3)

torch.manual_seed(RANDOM_SEED)
random_tensor2 = torch.rand(2, 3)

print(random_tensor1, random_tensor2, random_tensor1 == random_tensor2)


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]]) tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]]) tensor([[True, True, True],
        [True, True, True]])


In [110]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'