Creating Matrix


In [1]:
import numpy as np

In [2]:
m1 = np.array([[2, 3], [6, 7]])

In [7]:
m1.shape

(2, 2)

In [15]:
m1

array([[2, 3],
       [6, 7]])

In [8]:
m1.ndim

2

In [11]:
m2 = np.array([[1, 2, 11], [3, 4, 12], [5, 6, 13]])

In [12]:
m2.shape

(3, 3)

In [13]:
m2.ndim

2

In [14]:
m2

array([[ 1,  2, 11],
       [ 3,  4, 12],
       [ 5,  6, 13]])

Creating Matricess with Random values


In [17]:
m3 = np.random.rand(3, 3)

In [18]:
m3

array([[0.26325474, 0.74779939, 0.37464625],
       [0.84962145, 0.79548723, 0.73780657],
       [0.33188663, 0.40684858, 0.85381571]])

In [19]:
m4 = np.random.randint(10, 100, (2, 2))

In [20]:
m4

array([[92, 96],
       [35, 46]], dtype=int32)

Marix with all the values as 1


In [27]:
m1 = np.ones((5, 5), dtype=int)

In [28]:
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Matrix with all the values as 0


In [29]:
m2 = np.zeros((3, 3), dtype=int)

In [30]:
m2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Identity Matrix


In [38]:
m3 = np.eye(3, 3, dtype=int)

In [39]:
m3

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Transpose of a Matrix


In [40]:
m1 = np.random.randint(10, 20, (3, 3))

In [44]:
m1

array([[13, 12, 19],
       [18, 13, 17],
       [17, 14, 14]], dtype=int32)

In [45]:
m1.transpose() # np.transpose(m1)

array([[13, 18, 17],
       [12, 13, 14],
       [19, 17, 14]], dtype=int32)