In [1]:
import numpy as np

### Syntax: numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

### Creating a 1D Array from a List

In [8]:
my_list = [1, 2, 3, 4, 5]

array_1d = np.array(my_list)

print(f'1D array form List: {array_1d}')
print(f'Shape: {array_1d.shape}')
print(f'Data Type: {array_1d.dtype}')

1D array form List: [1 2 3 4 5]
Shape: (5,)
Data Type: int64


### Creating a 1D Array from a Tuple

In [10]:
my_tuple  = (10, 20, 30, 40)

arr_from_tuple = np.array(my_tuple)

print(f'1D array form List: {arr_from_tuple}')
print(f'Shape: {arr_from_tuple.shape}')
print(f'Data Type: {arr_from_tuple.dtype}')

1D array form List: [10 20 30 40]
Shape: (4,)
Data Type: int64


### Creating a 2D Array from a Nested List

In [11]:
nested_list=[[1, 2, 3], [4, 5, 6]]

arr_2d = np.array(nested_list)


print(f'1D array form List: {arr_2d}')
print(f'Shape: {arr_2d.shape}')
print(f'Data Type: {arr_2d.dtype}')

1D array form List: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data Type: int64


### Specifying Data Type

In [15]:
my_list = [1.22, 2.33, 3.44, 5.66]

arr_float=np.array(my_list, dtype=float)
# arr_float=np.array(my_list, dtype=np.int32)

print(f'1D array form List: {arr_float}')
print(f'Shape: {arr_float.shape}')
print(f'Data Type: {arr_float.dtype}')



1D array form List: [1.22 2.33 3.44 5.66]
Shape: (4,)
Data Type: float64


### Creating a 3D Array from Nested Lists

In [19]:
arr = [[[1, 2], [3, 4]], [[5, 6],[7, 8]]]
arr_3d=np.array(arr)

print(f'3D array form List: \n {arr_3d}')
print(f'Shape: {arr_3d.shape}')
print(f'Data Type: {arr_3d.dtype}')
print(f'Data Type: {arr_3d.ndim}')

3D array form List: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Data Type: int64
Data Type: 3


## Arrays with specific values (np.zeros, np.ones, np.full)

#### (shape, dtype=float, order='C')

#### Creating a 1D Array with np.zeros

In [20]:
arr = np.zeros(5)
print(f"Array \n {arr}")
print(f"Shape \n {arr.shape}")
print(f"Size \n {arr.size}")
print(f"Dimensions \n {arr.ndim}")

Array 
 [0. 0. 0. 0. 0.]
Shape 
 (5,)
Size 
 5
Dimensions 
 1


### Creating a 2D Array with np.ones

In [22]:
arr = np.ones((3,3), dtype=np.int32)
print(f"Array \n {arr}")
print(f"Shape \n {arr.shape}")
print(f"Size \n {arr.size}")
print(f"Dimensions \n {arr.ndim}")

Array 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Shape 
 (3, 3)
Size 
 9
Dimensions 
 2


### Creating a 3D Array with np.full

In [24]:
arr = np.full((3,3, 4), 2)
print(f"Array \n {arr}")
print(f"Shape \n {arr.shape}")
print(f"Size \n {arr.size}")
print(f"Dimensions \n {arr.ndim}")

Array 
 [[[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]
Shape 
 (3, 3, 4)
Size 
 36
Dimensions 
 3


## Arrays with ranges (np.arange, np.linspace, np.logspace)

#### np.arange(start, stop, step, dtype=None)

In [25]:
arr = np.arange(0,  10, 2)
print(arr)

[0 2 4 6 8]


#### np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None) 

In [26]:
arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


#### np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

In [28]:
arr = np.logspace(0, 10, 2)
print(arr)

[1.e+00 1.e+10]


## Identity and diagonal matrices (np.eye, np.diag)

#### np.eye(N, M=None, k=0, dtype=float, order='C')

In [29]:
arr =np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
arr=np.eye(3, 4, k=0, dtype=np.int32)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


#### np.diag(v, k=0) 

In [38]:
values=[1, 2, 3, 4, 5]
arr = np.diag(values)
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [40]:
values=[2, 3, 4, 5, 6]
arr = np.diag(values, k=1)
print(arr)

[[0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]
 [0 0 0 0 0 0]]


### Random arrays (np.random.rand, np.random.randn, np.random.randint)

#### np.random.rand

In [41]:
rand=np.random.rand(5)
print(rand)

[0.72919954 0.54589735 0.89239365 0.4328172  0.62998268]


In [43]:
rand=np.random.rand(3,2)
print(rand)
print(f"dimension\n{rand.ndim} ")

[[0.61227568 0.24307198]
 [0.0220875  0.32734441]
 [0.26814025 0.0145018 ]]
dimension
2 


#### np.random.randn(d0, d1, ..., dn)

In [44]:
randN = np.random.randn(5)
print(randN)

[ 0.01021086 -1.27072576 -0.17224567 -1.64860907 -0.89397006]


#### np.random.randint(low, high=None, size=None, dtype=int)

In [48]:
rand = np.random.randint(0, 10, size=(5, 3))
print(rand)

[[9 3 9]
 [4 3 2]
 [2 0 0]
 [9 0 4]
 [9 1 8]]


### Reshaping and Resizing

In [57]:
arr=np.array([1,2,3,4,5,6])
reshape=arr.reshape(3,-1)
print(reshape)
print(reshape.flatten())
print(reshape.ravel())

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


#### Transposeing 

In [59]:
arr = np.array([[1, 2, 3,9],[4, 5 ,6, 7]])
transpose=arr.transpose()
transpose_T= arr.T
print(transpose)
print(transpose_T)

[[1 4]
 [2 5]
 [3 6]
 [9 7]]
[[1 4]
 [2 5]
 [3 6]
 [9 7]]


In [60]:
arr = np.array([1, 2, 3])

# Resize to larger size (repeats elements)
resized = np.resize(arr, (5,))

print("Original Array:", arr)
print("Resized to (5,):", resized)

Original Array: [1 2 3]
Resized to (5,): [1 2 3 1 2]
