Numpy - Numarical Python

Adv

- Allow several Mathematical Operations
- Faster operations


In [1]:
import numpy as np

List vs Numpy Time Taken


In [12]:
from time import process_time

my_list=[i for i in range(10000000)]

start_time=process_time()

my_list=[i + 5 for i in my_list]

end_time=process_time()

print(end_time - start_time)



0.609375


In [13]:
np_array = np.array([i for i in range(10000000)])

start_time = process_time()

np_array += 5

end_time=process_time()

print(end_time - start_time)


0.015625


Numpy Arrays


In [18]:
list1 = [1, 2, 3, 4, 5]

print(f"List : \n {list1}")
print(f"type: \n {type(list1)}")


List : 
 [1, 2, 3, 4, 5]
type: 
 <class 'list'>


In [19]:
np_array= np.array([1, 2, 3, 4, 5])

print(f"Array: \n {np_array}")
print(f"Dtype: \n {type(np_array)}")

Array: 
 [1 2 3 4 5]
Dtype: 
 <class 'numpy.ndarray'>


Creating One Dimensional Array


In [20]:
a = np.array([1, 2, 3, 4, 5])

print(f"Np Array: \n {a}")
print(f"Shape: \n {a.shape}")

Np Array: 
 [1 2 3 4 5]
Shape: 
 (5,)


Two Dimensional Array


In [23]:
b = np.array([(1, 2), (3, 4), (5, 6)])
print(f"Np Array: \n {b}")
print(f"Shape: \n {b.shape}")
print(f"Dimensions: \n {b.ndim}")

Np Array: 
 [[1 2]
 [3 4]
 [5 6]]
Shape: 
 (3, 2)
Dimensions: 
 2


Float values with 2D array


In [24]:
c = np.array([(1, 2, 3), (4, 5, 5)], dtype=float)

print(f"Np Array: \n {c}")
print(f"Shape: \n {c.shape}")
print(f"Dimensions: \n {c.ndim}")


Np Array: 
 [[1. 2. 3.]
 [4. 5. 5.]]
Shape: 
 (2, 3)
Dimensions: 
 2


Initial Placeholders


create a Numpy Array of Zeros


In [25]:
x = np.zeros((4, 5))

print(f"Np Array: \n {x}")
print(f"Shape: \n {x.shape}")
print(f"Dimensions: \n {x.ndim}")

Np Array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Shape: 
 (4, 5)
Dimensions: 
 2


create Numpy Array of Ones


In [26]:
y = np.ones((3, 4))

print(f"Np Array: \n {y}")
print(f"Shape: \n {y.shape}")
print(f"Dimensions: \n {y.ndim}")

Np Array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: 
 (3, 4)
Dimensions: 
 2


create Numpy Array of Particular value


In [27]:
z = np.full((3, 3), 9)

print(f"Np Array: \n {z}")
print(f"Shape: \n {z.shape}")
print(f"Dimensions: \n {z.ndim}")

Np Array: 
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
Shape: 
 (3, 3)
Dimensions: 
 2


create Identity Matrix


In [29]:
a = np.eye(5)

print(f"Np Array: \n {a}")
print(f"Shape: \n {a.shape}")
print(f"Dimensions: \n {a.ndim}")

Np Array: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Shape: 
 (5, 5)
Dimensions: 
 2


create Numpy Array with Random Values


In [31]:
b = np.random.rand(3, 4)

print(f"Np Array: \n {b}")
print(f"Shape: \n {b.shape}")
print(f"Dimensions: \n {b.ndim}")

Np Array: 
 [[0.27432731 0.79452051 0.24875387 0.87230832]
 [0.41104186 0.3438218  0.73477066 0.47373176]
 [0.39114353 0.22773356 0.14373378 0.95119032]]
Shape: 
 (3, 4)
Dimensions: 
 2


create Numpy Array with Random Values with Integers


In [34]:
c = np.random.randint(0, 100, (3,4))

print(f"Np Array: \n {c}")
print(f"Shape: \n {c.shape}")
print(f"Dimensions: \n {c.ndim}")

Np Array: 
 [[35 44 39  5]
 [65 51  6  6]
 [53 77 16 37]]
Shape: 
 (3, 4)
Dimensions: 
 2


create of Evenly Spaced Values


In [37]:
d = np.linspace(10, 50, 5)

print(f"Np Array: \n {d}")
print(f"Shape: \n {d.shape}")
print(f"Dimensions: \n {d.ndim}")


Np Array: 
 [10. 20. 30. 40. 50.]
Shape: 
 (5,)
Dimensions: 
 1


array of evenly spaced value with step value


In [38]:
e = np.arange(10, 20, 2)


print(f"Np Array: \n {e}")
print(f"Shape: \n {e.shape}")
print(f"Dimensions: \n {e.ndim}")

Np Array: 
 [10 12 14 16 18]
Shape: 
 (5,)
Dimensions: 
 1


convert a List to numpy array


In [40]:
list2 = [10, 20, 30, 40, 50]

np_array = np.asarray(list2)


print(f"Np Array: \n {np_array}")
print(f"Shape: \n {np_array.shape}")
print(f"Dimensions: \n {np_array.ndim}")
print(f"Type: \n {type(np_array)}")

Np Array: 
 [10 20 30 40 50]
Shape: 
 (5,)
Dimensions: 
 1
Type: 
 <class 'numpy.ndarray'>


Analyzing Numpy Array


In [43]:
c = np.random.randint(10, 50, (5, 5))


print(f"Np Array: \n {c}")
print(f"Shape: \n {c.shape}")
print(f"Dimensions: \n {c.ndim}")
print(f"Size: \n {c.size}")
print(f"DType: \n {c.dtype}")

Np Array: 
 [[42 10 25 39 38]
 [30 24 19 10 26]
 [47 16 42 45 18]
 [16 31 32 46 30]
 [37 45 30 17 24]]
Shape: 
 (5, 5)
Dimensions: 
 2
Size: 
 25
DType: 
 int32


Mathematical operations on a np array


In [44]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [45]:
a = np.random.randint(10, 30, (4, 5))
b = np.random.randint(30, 60, (4, 5))

In [49]:
print(f"Adition \n {a + b} \n")
print(f"Subtraction \n {a - b} \n")
print(f"Multiplication \n {a * b} \n")
print(f"Division \n {a / b} \n")

Adition 
 [[65 56 77 71 66]
 [61 76 60 79 80]
 [59 50 60 45 57]
 [62 55 75 74 73]] 

Subtraction 
 [[-45 -30 -19 -15 -42]
 [-19 -24 -36 -37 -36]
 [-11 -12 -16 -19 -11]
 [ -4 -29 -41 -42 -45]] 

Multiplication 
 [[ 550  559 1392 1204  648]
 [ 840 1300  576 1218 1276]
 [ 840  589  836  416  782]
 [ 957  546  986  928  826]] 

Division 
 [[0.18181818 0.30232558 0.60416667 0.65116279 0.22222222]
 [0.525      0.52       0.25       0.36206897 0.37931034]
 [0.68571429 0.61290323 0.57894737 0.40625    0.67647059]
 [0.87878788 0.30952381 0.29310345 0.27586207 0.23728814]] 



In [52]:
print(f"Adition \n {np.add(a, b)} \n")
print(f"Subtraction \n {np.subtract(a, b)} \n")
print(f"Multiplication \n {np.multiply(a, b)} \n")
print(f"Division \n {np.divide(a, b)} \n")

Adition 
 [[65 56 77 71 66]
 [61 76 60 79 80]
 [59 50 60 45 57]
 [62 55 75 74 73]] 

Subtraction 
 [[-45 -30 -19 -15 -42]
 [-19 -24 -36 -37 -36]
 [-11 -12 -16 -19 -11]
 [ -4 -29 -41 -42 -45]] 

Multiplication 
 [[ 550  559 1392 1204  648]
 [ 840 1300  576 1218 1276]
 [ 840  589  836  416  782]
 [ 957  546  986  928  826]] 

Division 
 [[0.18181818 0.30232558 0.60416667 0.65116279 0.22222222]
 [0.525      0.52       0.25       0.36206897 0.37931034]
 [0.68571429 0.61290323 0.57894737 0.40625    0.67647059]
 [0.87878788 0.30952381 0.29310345 0.27586207 0.23728814]] 



Array Manipulation


In [54]:
array = np.random.randint(0, 10, (2, 3))


print(f"Np Array: \n {array} \n")
print(f"Shape: \n {array.shape} \n")
print(f"Dimensions: \n {array.ndim} \n")
print(f"Size: \n {array.size} \n")
print(f"DType: \n {array.dtype} \n")

Np Array: 
 [[7 6 7]
 [1 6 8]] 

Shape: 
 (2, 3) 

Dimensions: 
 2 

Size: 
 6 

DType: 
 int32 



Transpose


In [57]:
trans = np.transpose(array)
print(f"Trans \n {trans} \n")
print(f"Np Array: \n {trans} \n")
print(f"Shape: \n {trans.shape} \n")
print(f"Dimensions: \n {trans.ndim} \n")
print(f"Size: \n {trans.size} \n")
print(f"DType: \n {trans.dtype} \n")

Trans 
 [[7 1]
 [6 6]
 [7 8]] 

Np Array: 
 [[7 1]
 [6 6]
 [7 8]] 

Shape: 
 (3, 2) 

Dimensions: 
 2 

Size: 
 6 

DType: 
 int32 



In [58]:
trans2 = array.T

print(f"Trans \n {trans2} \n")
print(f"Np Array: \n {trans2} \n")
print(f"Shape: \n {trans2.shape} \n")
print(f"Dimensions: \n {trans2.ndim} \n")
print(f"Size: \n {trans2.size} \n")
print(f"DType: \n {trans2.dtype} \n")


Trans 
 [[7 1]
 [6 6]
 [7 8]] 

Np Array: 
 [[7 1]
 [6 6]
 [7 8]] 

Shape: 
 (3, 2) 

Dimensions: 
 2 

Size: 
 6 

DType: 
 int32 



Reshaping Array


In [59]:
a = np.random.randint(20, 40, (2, 4))


print(f"Np Array: \n {a} \n")
print(f"Shape: \n {a.shape} \n")
print(f"Dimensions: \n {a.ndim} \n")
print(f"Size: \n {a.size} \n")
print(f"DType: \n {a.dtype} \n")


Np Array: 
 [[30 29 31 36]
 [33 39 32 35]] 

Shape: 
 (2, 4) 

Dimensions: 
 2 

Size: 
 8 

DType: 
 int32 



In [62]:
b = a.reshape(4,2)

print(f"Np Array: \n {b} \n")
print(f"Shape: \n {b.shape} \n")
print(f"Dimensions: \n {b.ndim} \n")
print(f"Size: \n {b.size} \n")
print(f"DType: \n {b.dtype} \n")



Np Array: 
 [[30 29]
 [31 36]
 [33 39]
 [32 35]] 

Shape: 
 (4, 2) 

Dimensions: 
 2 

Size: 
 8 

DType: 
 int32 

