In [1]:
import numpy as np

In [5]:
a = np.random.randint(1, 10, 5)

s = 2

mult = s * a

print(f"A_matrix \n {a} \n")
print(f"Scalar \n {s} \n")
print(f"Mult \n {mult} \n")

A_matrix 
 [3 7 5 5 9] 

Scalar 
 2 

Mult 
 [ 6 14 10 10 18] 



In [6]:
np.multiply(s, a)

array([ 6, 14, 10, 10, 18], dtype=int32)