In [1]:
import numpy as np

In [2]:
a = np.random.randint(1, 10, ( 2, 2))
b = np.random.randint(1, 10, ( 2, 2))

mult = a * b

print(f"A_matrix \n {a} \n ")
print(f"B_matrix \n {b} \n ")
print(f"Mult \n {mult} \n ")

A_matrix 
 [[2 3]
 [7 4]] 
 
B_matrix 
 [[7 8]
 [7 1]] 
 
Mult 
 [[14 24]
 [49  4]] 
 


In [3]:
np.multiply(a , b)

array([[14, 24],
       [49,  4]], dtype=int32)