In [3]:
import numpy as np

In [4]:
a = np.array([[2, 3], [4, 5]])

b = np.array([[6, 7], [8, 9]])

sub = (a - b)

sub

array([[-4, -4],
       [-4, -4]])

In [5]:
c = np.random.randint(1, 10, (3, 3))

d = np.random.randint(10, 20, (3, 3))

sub = c - d

print(f" C_matrix \n {c} \n")
print(f" D_matrix \n  {d} \n")
print(f" SUB \n {sub} \n")

 C_matrix 
 [[4 4 7]
 [6 8 4]
 [1 4 1]] 

 D_matrix 
  [[14 10 12]
 [17 13 13]
 [17 12 11]] 

 SUB 
 [[-10  -6  -5]
 [-11  -5  -9]
 [-16  -8 -10]] 



In [6]:
np.subtract(c ,d)

array([[-10,  -6,  -5],
       [-11,  -5,  -9],
       [-16,  -8, -10]], dtype=int32)