In [1]:
import numpy as np

In [2]:
a = np.array([[2, 3], [4, 5]])

b = np.array([[6, 7], [8, 9]])

sum = (a + b)

sum

array([[ 8, 10],
       [12, 14]])

In [3]:
c = np.random.randint(1, 10, (3, 3))

d = np.random.randint(10, 20, (3, 3))

sum = c + d

print(f" C_matrix \n {c} \n")
print(f" D_matrix \n  {d} \n")
print(f" SUM \n {sum} \n")

 C_matrix 
 [[5 4 9]
 [2 3 3]
 [9 3 2]] 

 D_matrix 
  [[12 15 12]
 [19 10 19]
 [13 10 13]] 

 SUM 
 [[17 19 21]
 [21 13 22]
 [22 13 15]] 



In [6]:
np.add(a, b)

array([[ 8, 10],
       [12, 14]])